### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by h7ml** [EasyOC/easyoc-amis-admin#1]
```log
[20:25:38.582] Running build in San Francisco, USA (West) – sfo1
[20:25:38.635] Cloning github.com/h7ml/amis-page (Branch: main, Commit: ad94130)
[20:25:38.756] Previous build cache not available
[20:25:39.724] Cloning completed: 1.089s
[20:25:39.850] Running "vercel build"
[20:25:40.290] Vercel CLI 28.17.0
[20:25:40.869] Installing dependencies...
[20:25:41.165] yarn install v1.22.17
[20:25:41.180] warning package.json: "dependencies" has dependency "@types/node" with range "^16.11.11" that collides with a dependency in "devDependencies" of the same name with version "^11.13.8"
[20:25:41.188] info No lockfile found.
[20:25:41.193] warning easyoc-amis-admin@2.0.0: "dependencies" has dependency "@types/node" with range "^16.11.11" that collides with a dependency in "devDependencies" of the same name with version "^11.13.8"
[20:25:41.195] [1/4] Resolving packages...
[20:25:44.704] warning react-router > mini-create-react-context@0.3.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[20:25:45.150] warning @types/history@5.0.0: This is a stub types definition. history provides its own type definitions, so you do not need this installed.
[20:25:45.359] warning @types/react-router > @types/history@5.0.0: This is a stub types definition. history provides its own type definitions, so you do not need this installed.
[20:25:45.648] warning @vue/compiler-sfc > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[20:25:46.858] [2/4] Fetching packages...
[20:26:05.849] warning swr@2.1.0: The engine "pnpm" appears to be invalid.
[20:26:05.858] [3/4] Linking dependencies...
[20:26:05.861] warning "@ant-design/pro-components > @ant-design/pro-form@2.9.0" has unmet peer dependency "rc-field-form@^1.22.0".
[20:26:05.861] warning "@ant-design/pro-components > @ant-design/pro-table@3.5.2" has unmet peer dependency "rc-field-form@^1.22.0".
[20:26:05.862] warning "@ant-design/pro-components > @ant-design/pro-utils > react-sortable-hoc@2.0.0" has unmet peer dependency "prop-types@^15.5.7".
[20:26:05.862] warning "@ant-design/pro-components > @ant-design/pro-utils > react-sortable-hoc@2.0.0" has incorrect peer dependency "react@^16.3.0 || ^17.0.0".
[20:26:05.862] warning "@ant-design/pro-components > @ant-design/pro-utils > react-sortable-hoc@2.0.0" has incorrect peer dependency "react-dom@^16.3.0 || ^17.0.0".
[20:26:05.862] warning " > mobx-react@6.3.1" has incorrect peer dependency "react@^16.8.0 || 16.9.0-alpha.0".
[20:26:05.863] warning "amis > react-json-view@1.21.3" has incorrect peer dependency "react@^17.0.0 || ^16.3.0 || ^15.5.4".
[20:26:05.863] warning "amis > react-json-view@1.21.3" has incorrect peer dependency "react-dom@^17.0.0 || ^16.3.0 || ^15.5.4".
[20:26:05.863] warning "amis > video-react@0.15.0" has incorrect peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0".
[20:26:05.863] warning "amis > video-react@0.15.0" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0 || ^17.0.0".
[20:26:05.864] warning "amis > amis-ui > react-textarea-autosize@8.3.3" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
[20:26:05.864] warning "amis > react-json-view > flux@4.0.4" has incorrect peer dependency "react@^15.0.2 || ^16.0.0 || ^17.0.0".
[20:26:05.865] warning "amis > mobx-react > mobx-react-lite@2.2.2" has incorrect peer dependency "react@^16.8.0".
[20:26:05.866] warning " > amis-editor@5.2.5" has unmet peer dependency "amis-theme-editor@*".
[20:26:05.866] warning "amis-editor > amis-theme-editor@2.0.10" has unmet peer dependency "amis-theme-editor-helper@*".
[20:26:05.868] warning " > mobx-react-lite@3.4.3" has incorrect peer dependency "mobx@^6.1.0".
[20:26:05.868] warning "react-router > mini-create-react-context@0.3.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0".
[20:26:05.869] warning " > css-loader@6.7.3" has unmet peer dependency "webpack@^5.0.0".
[20:26:05.870] warning " > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[20:26:05.870] warning " > less-loader@11.1.0" has unmet peer dependency "webpack@^5.0.0".
[20:26:05.870] warning " > style-loader@3.3.2" has unmet peer dependency "webpack@^5.0.0".
[20:26:05.870] warning " > ts-loader@9.4.2" has unmet peer dependency "webpack@^5.0.0".
[20:26:05.870] warning " > url-loader@4.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[20:26:28.863] [4/4] Building fresh packages...
[20:26:29.472] success Saved lockfile.
[20:26:29.478] Done in 48.32s.
[20:26:29.932] [36mvite v4.2.1 [32mbuilding for production...[36m[39m
[20:26:29.947] [32m✓[39m 0 modules transformed.
[20:26:29.947] [32m✓[39m built in 14ms
[20:26:29.948] [31mCould not resolve entry module "src/editor/index.html".[39m
[20:26:29.950] [31merror during build:
[20:26:29.950] RollupError: Could not resolve entry module "src/editor/index.html".
[20:26:29.950]     at error (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
[20:26:29.950]     at ModuleLoader.loadEntryModule (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:23797:20)
[20:26:29.950]     at async Promise.all (index 1)[39m
[20:26:29.967] Error: Command "vite build" exited with 1
[20:26:30.184] BUILD_UTILS_SPAWN_1: Command "vite build" exited with 1
```

**Comment by hyzx86** [comment]
用的 vite？

**Comment by h7ml** [comment]
是的。

**Comment by hyzx86** [comment]
为什么 你这输出的 内容里 有这个？开着代理呢？

[20:25:38.582] Running build in San Francisco, USA (West) – sfo1

**Comment by hyzx86** [comment]
还是 在 codespace 里面用的？

**Comment by hyzx86** [comment]
试试手工设置下 pnpm 源吧
